export interface TestSiteInterface {
  type: number;
  title: string;
  countrycode: string;
  location: [number, number];
  text: string;
}

export const countries = [
  { name: "US", color: "#ef5777" },
  { name: "USUK", color: "#575fcf" },
  { name: "FR", color: "#4bcffa" },
  { name: "SU", color: "#34e7e4" },
  { name: "UK", color: "#0be881" },
  { name: "IN", color: "#ffc048" },
  { name: "CN", color: "#ffdd59" },
  { name: "PK", color: "#9D8DF1" },
  { name: "KP", color: "#1CFEBA" },
];

export const geojson = [
  {
    type: 8,
    title: "Amchitka Island, Alaska, USA",
    countrycode: "US",
    location: [51.456, 179.102],
    text:
      "3 underground tests conducted in the 1960s and early 1970s. Closed in 1971. ",
  },
  {
    type: 8,
    title: "Nevada Test Site, Nevada, USA",
    countrycode: "USUK",
    location: [38.505191, -117.026367],
    text:
      "904 tests, including 23 peaceful nuclear explosions, conducted by the United States between 1951 and 1992, making it the site of the greatest number of tests in the world. In addition, 24 underground tests conducted by the United Kingdom between 1962 and 1991. From 1958 onwards the testing programme of the United Kingdom was closely coordinated with that of the United States through the US-UK Mutual Defense Agreement.",
  },
  {
    type: 8,
    title: "Fallon, Nevada, USA",
    countrycode: "US",
    location: [39.2, -118.381],
    text: "1 underground test in 1963.",
  },
  {
    type: 8,
    title: "Carlsbad, New Mexico, USA",
    countrycode: "US",
    location: [32.264, -103.866],
    text: "Site of one peaceful nuclear explosion in 1961.",
  },
  {
    type: 8,
    title: "Hattiesburg, Mississippi, USA",
    countrycode: "US",
    location: [31.142, -89.57],
    text: "2 underground tests in 1964.",
  },
  {
    type: 8,
    title: "Open Sea, South Atlantic Ocean",
    countrycode: "US",
    location: [-38.5, -11.5],
    text: "3 tests, detonated from rockets, conducted in 1958.",
  },
  {
    type: 8,
    title: "Reggane, Sahara Desert, Algeria",
    countrycode: "FR",
    location: [26.19, 0.04],
    text: "4 atmospheric tests between 1960 and 1961. Closed. ",
  },
  {
    type: 8,
    title: "Rifle, Colorado, USA",
    countrycode: "US",
    location: [39.793, -108.368],
    text: "Site of one peaceful nuclear explosion in 1973.",
  },
  {
    type: 8,
    title: "Grand Valley, Colorado, USA",
    countrycode: "US",
    location: [39.356, -107.949],
    text: "Site of one peaceful nuclear explosion in 1969.",
  },
  {
    type: 8,
    title: "In Ekker, Algeria",
    countrycode: "FR",
    location: [24.023261, 5.072937],
    text: "13 underground tests between 1961 and 1966. Closed.",
  },
  {
    type: 8,
    title: "Alamogordo, New Mexico, USA",
    countrycode: "US",
    location: [32.879587, -105.963821],
    text: 'Site of the world’s first nuclear test, "Trinity", on 16 July 1945.',
  },
  {
    type: 8,
    title: "Enewetak Atoll, Marshall Islands",
    countrycode: "US",
    location: [11.556, 162.354],
    text:
      '43 tests conducted between 1948 and 1958, including the world’s first hydrogen detonation, ("MIKE"] in 1952. Closed in 1958. ',
  },
  {
    type: 8,
    title: "Bikini Atoll, Marshall Islands",
    countrycode: "US",
    location: [11.496, 162.371],
    text:
      '23 tests conducted between 1946 and 1956, including the largest nuclear weapon ever detonated by the United States, the "Castle Bravo" in 1954, which created the worst radiological disaster in US testing history. Closed in 1958.',
  },
  {
    type: 8,
    title: "Johnston Island",
    countrycode: "US",
    location: [16.358, 169.536],
    text:
      "12 atmospheric tests conducted between 1958 and 1962. Closed in 1993.",
  },
  {
    type: 8,
    title: "Christmas Island, Kiribati",
    countrycode: "USUK",
    location: [2, -157],
    text:
      "33 atmospheric tests conducted in the 1950s and early 1960s by the United States and the United Kingdom (9 tests in 1957-58], including the first UK thermonuclear detonation in 1957. Closed in 1969.",
  },
  {
    type: 8,
    title: "Farmington, New Mexico, USA",
    countrycode: "US",
    location: [36.678, -107.209],
    text: "Site of one peaceful nuclear explosion in 1967.",
  },
  {
    type: 8,
    title: "Nellis Air Force Range, Nevada, USA",
    countrycode: "US",
    location: [37.154, -116.077],
    text: "5 tests between 1957 and 1963.",
  },
  {
    type: 8,
    title: "Central Nevada, USA",
    countrycode: "US",
    location: [38.634, -118.113],
    text: "1 underground test in 1968.",
  },
  {
    type: 8,
    title: "Nagasaki, Japan",
    countrycode: "US",
    location: [32.825365, 129.865265],
    text:
      "Site of the second nuclear weapon used for military purposes in wartime, 9 August 1945.",
  },
  {
    type: 8,
    title: "Hiroshima, Japan",
    countrycode: "US",
    location: [34.470335, 132.456665],
    text:
      "Site of the first nuclear weapon used for military purposes in wartime, 6 August 1945.",
  },
  {
    type: 8,
    title: "Semipalatinsk, Kazakhstan",
    countrycode: "SU",
    location: [50.410952, 80.254397],
    text:
      '456 tests and peaceful nuclear explosions (7] conducted between 1949 and 1989, making it the site of the second greatest number of tests in the world. Site of the first USSR test, "Joe 1", in 1949, and the first USSR hydrogen bomb in 1953. Closed in 1991.',
  },
  {
    type: 8,
    title: "Novaya Zemlya Island",
    countrycode: "SU",
    location: [74, 56],
    text:
      '130 tests conducted between 1955 and 1990. Making it the site of the fourth greatest number of tests in the world. "Tsar Bomba", the largest nuclear bomb ever exploded, was tested here in 1961. ',
  },
  {
    type: 8,
    title: "Montebello Islands, Australia",
    countrycode: "UK",
    location: [-20.411569, 115.554886],
    text: "3 atmospheric tests conducted between 1952 and 1956. Closed.",
  },
  {
    type: 8,
    title: "Emu Field, Australia",
    countrycode: "UK",
    location: [-29, 132],
    text: "2 atmospheric tests in 1953. Closed.",
  },
  {
    type: 8,
    title: "Maralinga Test Range, Australia",
    countrycode: "UK",
    location: [-30.166667, 131.616667],
    text: "7 atmospheric tests in 1956-57. Closed. Clean-up completed in 1967.",
  },
  {
    type: 8,
    title: "Mururoa Atoll, French Polynesia",
    countrycode: "FR",
    location: [-21.833333, -138.916667],
    text:
      "179 tests (42 atmospheric and 137 underground] between 1966 and 1996, making it the third site of the greatest number of tests in the world. Closed in 1999.",
  },
  {
    type: 8,
    title: "Fangataufa Atoll, French Polynesia",
    countrycode: "FR",
    location: [-22.25, -138.75],
    text:
      '14 tests (4 atmospheric and 10 underground] conducted between 1966 and 1996, including the first French hydrogen/thermonuclear bomb, "Canopus", in 1968, the largest explosion ever detonated by France. After this test, the atoll was declared off-limits due to heavy contamination. Closed in 1999.',
  },
  {
    type: 8,
    title: "Lop Nur, Xinjiang Province, China",
    countrycode: "CN",
    location: [40.083333, 90.083333],
    text:
      "Site of 45 tests conducted by China between 1964 and 1996, including the first hydrogen bomb in 1966, and the first thermonuclear bomb in 1968. All tests were atmospheric until 1980, then changed to underground testing. ",
  },
  {
    type: 8,
    title: "Pokharan, Rajastan Desert, India",
    countrycode: "IN",
    location: [26.92, 71.92],
    text: "3 underground tests on 18 May 1974 and on 11 and 13 May 1998.",
  },
  {
    type: 8,
    title: "Ras Koh, Chagai Hills, Baluchistan, Pakistan",
    countrycode: "PK",
    location: [28.862, 64.818],
    text: "2 underground tests on 28 and 30 May 1998.",
  },
  {
    type: 8,
    title: "Kimchaek, North Korea",
    countrycode: "KP",
    location: [41.3119, 129.0189],
    text: "1 announced underground test on 9 October 2006.",
  },
  {
    type: 8,
    title: "Open Sea, South Pacific Ocean ",
    countrycode: "US",
    location: [28.733, -126.267],
    text: "Site of an underwater test in 1955.",
  },
  {
    type: 8,
    title: "Open Sea, South Pacific Ocean ",
    countrycode: "US",
    location: [12.617, 163.017],
    text: "Site of a balloon test in 1958.",
  },
  {
    type: 8,
    title: "Open Sea, South Pacific Ocean ",
    countrycode: "US",
    location: [4.833, -149.417],
    text: "Site of a test detonated from a rocket in 1962.",
  },
  {
    type: 8,
    title: "Open Sea, South Pacific Ocean ",
    countrycode: "US",
    location: [31.233, -124.217],
    text: "Site of an underwater test in 1962.",
  },
  {
    type: 8,
    title: "Ukraine",
    countrycode: "SU",
    location: [49.8, 35.4],
    text: "Site of two peaceful nuclear explosions in 1972 and 1979.",
  },
  {
    type: 8,
    title: "Uzbekistan",
    countrycode: "SU",
    location: [38.968, 64.517],
    text: "Site of two peaceful nuclear explosions in 1966 and 1968.",
  },
  {
    type: 8,
    title: "Turkmenistan",
    countrycode: "SU",
    location: [37.35, 62.05],
    text: "Site of one peaceful nuclear explosion in 1972. ",
  },
  {
    type: 8,
    title: "Aralsk, Kazakhstan",
    countrycode: "SU",
    location: [46, 62],
    text: "One atmospheric test in 1956. ",
  },
  {
    type: 8,
    title: "Astrakham, RSFSR",
    countrycode: "SU",
    location: [46.757, 48.275],
    text: "Site of 15 peaceful nuclear explosions between 1980 and 1984. ",
  },
  {
    type: 8,
    title: "Perm, RSFSR",
    countrycode: "SU",
    location: [57.22, 55.393],
    text: "Site of 8 peaceful nuclear explosions between 1969 and 1987. ",
  },
  {
    type: 8,
    title: "Bashkir, RSFSR",
    countrycode: "SU",
    location: [52.9, 56.5],
    text: "Site of 6 peaceful nuclear test explosions between 1965 and 1980. ",
  },
  {
    type: 8,
    title: "Orenburg, RSFSR",
    countrycode: "SU",
    location: [52.127, 51.994],
    text:
      "Site 1 atmospheric test (1954] and 5 peaceful nuclear explosions (1970-1973]. ",
  },
  {
    type: 8,
    title: "Arkhangelsk, RSFSR",
    countrycode: "SU",
    location: [61.358, 48.092],
    text: "Site of 4 peaceful nuclear explosions between 1971 and 1988. ",
  },
  {
    type: 8,
    title: "Komi, RSFSR",
    countrycode: "SU",
    location: [67.283, 63.467],
    text: "Site of 4 peaceful nuclear explosions between 1971 and 1984. ",
  },
  {
    type: 8,
    title: "Murmansk, RSFSR",
    countrycode: "SU",
    location: [67.75, 33.1],
    text: "Site of 2 peaceful nuclear explosions in 1972 and 1984. ",
  },
  {
    type: 8,
    title: "Stavropol, RSFSR",
    countrycode: "SU",
    location: [45.848, 42.6],
    text: "Site of one peaceful nuclear explosion in 1969. ",
  },
  {
    type: 8,
    title: "Ivanovo, RSFSR",
    countrycode: "SU",
    location: [57.508, 42.643],
    text: "Site of one peaceful nuclear explosion in 1971. ",
  },
  {
    type: 8,
    title: "Kalmik, RSFSR",
    countrycode: "SU",
    location: [46.853, 44.923],
    text: "Site of one peaceful nuclear explosion in 1972. ",
  },
  {
    type: 8,
    title: "Kemerevo, RSFSR",
    countrycode: "SU",
    location: [55.834, 87.526],
    text: "Site of one peaceful nuclear explosion in 1984. ",
  },
  {
    type: 8,
    title: "Jakutsk, RSFSR",
    countrycode: "SU",
    location: [66.1, 112.65],
    text: "Site of 12 peaceful nuclear explosions between 1974 and 1987. ",
  },
  {
    type: 8,
    title: "Krasnoyarsk, RSFSR",
    countrycode: "SU",
    location: [69.578, 90.337],
    text: "Site of 9 peaceful nuclear explosions between 1975 and 1982. ",
  },
  {
    type: 8,
    title: "Tyuemn, RSFSR",
    countrycode: "SU",
    location: [57.7, 65.2],
    text: "Site of 8 peaceful nuclear explosions between 1967 and 1988. ",
  },
  {
    type: 8,
    title: "Irkutsk, RSFSR",
    countrycode: "SU",
    location: [57.29, 106.23],
    text: "Site of 2 peaceful nuclear explosions in 1977 and 1982. ",
  },
  {
    type: 8,
    title: "Chita, RSFSR",
    countrycode: "SU",
    location: [50.955, 110.983],
    text: "Site of one peaceful nuclear explosion in 1977. ",
  },
  {
    type: 8,
    title: "Azgir, Kazakhstan",
    countrycode: "SU",
    location: [47.8, 79.0],
    text: "Site of 17 peaceful nuclear explosions between 1966 and 1979. ",
  },
  {
    type: 8,
    title: "Uralsk, Kazahstan",
    countrycode: "SU",
    location: [51.363, 53.306],
    text: "Site of 6 peaceful nuclear explosions between 1983 and 1984.",
  },
  {
    type: 8,
    title: "Mangishlak, Kazakhstan",
    countrycode: "SU",
    location: [43.867, 54.8],
    text: "Site of 3 peaceful nuclear explosions between 1969 and 1970. ",
  },
  {
    type: 8,
    title: "Kustonay, Kazakhstan",
    countrycode: "SU",
    location: [49.4, 48.142],
    text: "Site of one peaceful nuclear explosion in 1972. ",
  },
  {
    type: 8,
    title: "Tselinograd, Kazakhstan ",
    countrycode: "SU",
    location: [45.758, 67.825],
    text: "Site of 2 peaceful nuclear explosions in 1973. ",
  },
  {
    type: 8,
    title: "Djezkazgan, Kazakhstan",
    countrycode: "SU",
    location: [42.775, 67.408],
    text: "Site of one peaceful nuclear explosion in 1973. ",
  },
  {
    type: 8,
    title: "Aktyubinsk, Kazakhstan",
    countrycode: "SU",
    location: [47.605, 56.227],
    text: "Site of one peaceful nuclear explosion in 1987.",
  },
  {
    type: 8,
    title: "Missile Testing Range, RSFSR",
    countrycode: "SU",
    location: [49, 46],
    text: "Site of 10 atmospheric tests between 1956 and 1962.",
  },
];
